script-opts=ytdl_hook-ytdl_path=/home/kayode/.local/bin/yt-dlp
osc=yes
fullscreen=no
force-window=immediate
save-position-on-quit
cache=yes
demuxer-max-bytes=512MiB
demuxer-readahead-secs=20
alang=pt,por,portuguese
slang=pt,pt-br,por,portuguese,en,eng,english
sub-visibility=no
ytdl-format="((bestvideo[height<=?1080])+(bestaudio[format_note*=original]/bestaudio))/best"
keep-open=yes
border=no
#sub-auto=fuzzy
#ytdl-raw-options=ignore-config=,sub-lang="^pt*,^en*",write-sub=,write-auto-sub=
